### ISSUE TITLE
Tool installation unknown tool is unnecesarily fatal

### ISSUE THREAD

**Issue by erasche** [galaxyproject/ephemeris#133]
Currently some bioblend errors are fatal errors. It would be useful to us if they became non-fatal errors. With the large tool lists having them fail intermittently due to connection, or in this case unknown tool, errors isn't optimal. Logging the errors, continuing, and exiting with a non-zero code would be preferrable

```
	Repository autodock_vina_prepare_box is already installed.
	repository autodock_vina_prepare_box installed successfully (in 0:00:07.737768) at revision 4f7c5cad3377
(81/85) repository autodock_vina_prepare_box already installed at revision 761762031eee. Skipping.
Traceback (most recent call last):
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/bin/shed-tools", line 10, in <module>
    sys.exit(main())
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 744, in main
    install_tool_manager.install_repositories()
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 572, in install_repositories
    repository = self.get_changeset_revision(repository)
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 720, in get_changeset_revision
    installable_revisions = ts.repositories.get_ordered_installable_revisions(repository['name'], repository['owner'])
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bioblend/toolshed/repositories/__init__.py", line 149, in get_ordered_installable_revisions
    r = self._get(url=url, params=params)
  File "/home/centos/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 136, in _get
    status_code=r.status_code)
bioblend.ConnectionError: GET: error 404: '{"status": "error", "message": "No repository named get_pdb found with owner bgruening"}', 0 attempts left: {"status": "error", "message": "No repository named get_pdb found with owner bgruening"}
Installing any updated versions of europe-custom.yaml.lock
```

**Comment by rhpvorderman** [comment]
Or retry on connection errors. Maybe with some code like this:
```python
for i in NUMBER_OF_RETRIES:
    try:
        bioblend_api_call()
        break
    except bioblend.ConnectionError:
         log.warning("connection error! Retrying...")
         # We now should continue with the for loop as if nothing happened.
else:  # No break
    raise FatalError(f"Failed after {NUMBER_OF_RETRIES} retries." 
```

**Comment by erasche** [comment]
@rhpvorderman I've already proposed that that be included in bioblend by default, but as of yet we have not had time for it. Including this in ephemeris is suboptimal compared to fixing it for everyone. https://github.com/galaxyproject/bioblend/pull/266

**Comment by rhpvorderman** [comment]
@erasche whoops yes, I remember we discussed this already here https://github.com/galaxyproject/ephemeris/issues/98.
