### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4576-4577: ordinal not in range(128)

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/ephemeris#148]
I guess something in the TS response has changed with 19.09?

```
(18/670) Installing repository anova from lecorguille to section "Statistics" at revision bcd05315efc5 (TRT: 0:01:34.047112)
Traceback (most recent call last):
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/bin/shed-tools", line 10, in <module>
    sys.exit(main())
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 586, in main
    **kwargs)
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 191, in install_repositories
    result = self.install_repository_revision(repository, log)
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 412, in install_repository_revision
    if default_err_msg in str(e):
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bioblend/__init__.py", line 101, in __str__
    return "{0}: {1}".format(self.args[0], self.body)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4576-4577: ordinal not in range(128)
Installing any updated versions of cheminformatics.yaml.lock
Storing log file in: /tmp/ephemeris_j4coSE
(1/154) Installing repository rdock_rbdock from bgruening to section "ChemicalToolBox" at revision 1a1600fde77a (TRT: 0:00:32.015854)
	Repository rdock_rbdock is already installed.
	repository rdock_rbdock installed successfully (in 0:00:01.955625) at revision 1a1600fde77a
(2/154) Installing repository rdock_rbdock from bgruening to section "ChemicalToolBox" at revision 5f291eef9ef3 (TRT: 0:00:33.971989)
Traceback (most recent call last):
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/bin/shed-tools", line 10, in <module>
    sys.exit(main())
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 586, in main
    **kwargs)
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 191, in install_repositories
    result = self.install_repository_revision(repository, log)
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 412, in install_repository_revision
    if default_err_msg in str(e):
  File "/data/shiningpanda/jobs/023ca033/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bioblend/__init__.py", line 101, in __str__
    return "{0}: {1}".format(self.args[0], self.body)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4576-4577: ordinal not in range(128)
Installing any updated versions of tools_galaxyp.yaml.lock
```

**Comment by rhpvorderman** [comment]
Hmm. Seems some unicode is in the body. But python2 uses ascii strings by default.

Do you get the same errors when running python3 ephemeris? If not, this problem should be fixable by prepending `u` in front of strings to make python2 aware of the unicode (in bioblend or ephemeris, wherever the error is).
