### ISSUE TITLE
run-data-managers - need help

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/ephemeris#151]
```
run-data-managers -a yoooooo -g http://192.168.XXX.XXX:8080 --config run_data_managers.yaml -v
```

My run_data_managers.yaml 
```yaml
data_managers:
    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_mothur_toolsuite/data_manager_fetch_mothur_reference_data/0.1.3
      params:
        - 'data_source|data_source_selector': 'mothur_website'
        - 'data_source|ref_data': '{{ item.id }}'
      items:
        - id: lookup_gsflx
        - id: lookup_gs20
        - id: RDP_v16
        - id: RDP_v14
        - id: RDP_v10
        - id: RDP_v9
        - id: RDP_v7
        - id: RDP_v6
        - id: silva_release_128
        - id: silva_release_123
        - id: silva_release_119
        - id: silva_release_102
        - id: greengenes_August2013
        - id: greengenes_May2013
        - id: greengenes_old
        - id: greengenes_gold_alignment
        - id: secondary_structure_maps_silva
        - id: secondary_structure_maps_greengenes
      data_table_reload:
        - mothur_aligndb
        - mothur_lookup
        - mothur_map
        - mothur_taxonomy
```

The std
```
Storing log file in: /var/folders/bm/3wkhsl3j1h747_jm4xthmh980000kd/T/ephemeris_C7zD9s
Running data managers that populate the following source data tables: ['all_fasta']
Running data managers that index sequences.
Traceback (most recent call last):
  File "/Users/lecorguille/.venv_planemo/bin/run-data-managers", line 11, in <module>
    sys.exit(main())
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/ephemeris/run_data_managers.py", line 314, in main
    data_managers.run(log, args.ignore_errors, args.overwrite)
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/ephemeris/run_data_managers.py", line 274, in run
    run_jobs(self.index_jobs, self.skipped_index_jobs)
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/ephemeris/run_data_managers.py", line 256, in run_jobs
    tool_inputs=job["inputs"])
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/bioblend/galaxy/tools/__init__.py", line 127, in run_tool
    return self._tool_post(payload)
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/bioblend/galaxy/tools/__init__.py", line 233, in _tool_post
    return self._post(payload, files_attached=files_attached)
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 152, in _post
    files_attached=files_attached)
  File "/Users/lecorguille/.venv_planemo/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 146, in make_post_request
    body=r.text, status_code=r.status_code)
bioblend.ConnectionError: Unexpected HTTP status code: 400: {"err_msg": "Tool not found or not accessible.", "err_code": 0}
```

The tool seems installed
<img width="373" alt="Capture d’écran 2019-11-27 à 12 25 37" src="https://user-images.githubusercontent.com/11072022/69719570-0c7f3180-1111-11ea-9aa7-a8d73776e353.png">

Any idea?

Other question: do you know why `['all_fasta']` in `Running data managers that populate the following source data tables: ['all_fasta']`?

**Comment by mvdbeek** [comment]
The id looks correct, is this an admin API key (It can't be the master API key) ?

> Other question: do you know why `['all_fasta']` in `Running data managers that populate the following source data tables: ['all_fasta']`?

Data managers creating entries in all_fasta are always run first. The entries produced by them may be inputs to the next data manager ... it's not that this is actually run though, it's just a confusing log message.

**Comment by lecorguille** [comment]
> The id looks correct, is this an admin API key (It can't be the master API key) ?
AH!
It's indeed better with my API key.
In the context of CI, the master API key was a good solution.
I guess that we will create a "fake" admin account
